sudo: false

jobs:

  include:

    - stage: test

      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
      name: Run units tests
      script: yarn test

    - stage: docker
      if: branch = master
      services:
        - docker
        - rabbitmq
      env:
        - APP_RABBITMQ_USER=guest
        - APP_RABBITMQ_PASS=guest
      name: Build the image
      script: ./tasks/docker/build.sh $TRAVIS_COMMIT
    - script: ./tasks/docker/test.sh
      name: Run specs tests the image
