jobs:

  include:

    - stage: tests

      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
      name: Run units tests
      script: yarn test

    - stage: build
      branches:
        only:
        - master
      sudo: required
      services:
        - docker
        - rabbitmq
      env:
        - APP_RABBITMQ_USER=guest
        - APP_RABBITMQ_PASS=guest
      name: Build, Tests the docker image
      script:
        - ./tasks/docker/build.sh $TRAVIS_COMMIT
        - sudo ./tasks/docker/test.sh
