sudo: false

jobs:
  
  include:

    - stage: test
      name: Tests unit
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
      script: yarn test

    - stage: build
      if: branch = master
      name: Build docker image
      script: yarn docker:build $TRAVIS_COMMIT
