version: 2

aliases:

  - &use_node
    docker:
      - image: circleci/node:8

  - &use_env
    environment:
      ECS_APP: godzilla
      ECS_CLUSTER: ecs-cluster-frontend

  - &use_docker
    docker:
      - image: gperreymond/docker-awscli
      - image: rabbitmq:3-management-alpine
        environment:
          RABBITMQ_DEFAULT_USER: "infra"
          RABBITMQ_DEFAULT_PASS: "infra"
          RABBITMQ_DEFAULT_VHOST: "/"

  - &step_build_image
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Build docker image
          command: ./tasks/docker/build.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - images

  - &step_test_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Test docker image
          command: ./tasks/docker/test.sh
  - &step_push_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Push docker image
          command: ./tasks/docker/push.sh

jobs:

  # Tests
  tests:
    <<: *use_node
    steps:
      - checkout
      - run:
          name: Install node dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test

  # Build docker image
  docker_build:
    <<: *use_docker
    <<: *use_env
    <<: *step_build_image
  # Run tests specs on docker image
  docker_test:
    <<: *use_docker
    <<: *use_env
    <<: *step_test_image
  # Push docker image
  docker_push:
    <<: *use_docker
    <<: *use_env
    <<: *step_push_image

workflows:

  version: 2

  ci-test:
    jobs:
      - tests:
          filters:
            branches:
              ignore: master

  ci-deploy:
    jobs:
      - tests:
          filters:
            branches:
              only: master
      - docker_build:
          requires:
            - tests
